export const FeedData = [
  {
    id: "1",
    user: "John Doe",
    skillset: "Graphic Design",
    icon: "JD",
    text: "Just wrapped up a new brand identity project for a local coffee shop ☕🎨. It’s crazy how much a consistent color palette and typography can change the perception of a small business. I experimented with a warm earthy palette, custom hand-drawn icons, and playful typography. The client was thrilled, and honestly, I learned that simple design choices often have the biggest impact. Thinking of writing a step-by-step breakdown of the process — would that be helpful?",
    tags: ["Public Speaking", "Information Technology"],
    recSkill: ["Design Kit - Human Interaction", "Benching the Instagram"],
  },
  {
    id: "2",
    user: "Amaka I.",
    skillset: "Mobile Development",
    icon: "AI",
    text: "React Native has been such a game changer for me. I managed to build an MVP in under 3 weeks! 🚀 The most interesting part was balancing performance between iOS and Android, especially when handling animations. I also experimented with Expo and bare workflow — Expo is fast for prototyping, but bare workflow gave me more control. Curious how other devs handle navigation at scale though — stack vs tabs, what’s your preference?",
    tags: ["React Native", "Cross-Platform"],
    recSkill: ["Firebase Authentication", "Async Storage Best Practices"],
  },
  {
    id: "3",
    user: "David K.",
    skillset: "Content Writing",
    icon: "DK",
    text: "Lately I’ve been experimenting with storytelling in product copy. Instead of just describing features, I frame them as mini-stories that connect emotionally with the reader. For example, instead of saying ‘This app helps you save money,’ I write something like ‘Imagine never stressing about bills again — our app helps you take back control of your finances.’ Engagement rates went up by 32%! 📈 I’ll keep sharing insights as I test different tones and formats.",
    tags: ["Marketing", "Storytelling"],
    recSkill: ["Copywriting for UX", "SEO Deep Dive"],
  },
  {
    id: "4",
    user: "Fatima Z.",
    skillset: "UI/UX Design",
    icon: "FZ",
    text: "I spent the past week running user interviews for a new fintech app, and the insights were mind-blowing 🤯. Users don’t actually care about fancy dashboards — they just want clarity and confidence when making financial decisions. That means stripping away unnecessary UI clutter and focusing on direct communication. Sometimes the hardest part of design is unlearning what we think ‘looks good’ and focusing instead on what *feels natural* to the user.",
    tags: ["User Research", "Fintech"],
    recSkill: ["Figma Prototyping", "Heuristic Evaluation"],
  },
  {
    id: "5",
    user: "Kelvin O.",
    skillset: "Fullstack Development",
    icon: "KO",
    text: "Been deep-diving into backend optimization with Node.js and MongoDB 🔥. Learned the hard way that indexing isn’t optional when handling thousands of requests per minute. After proper indexing, response times dropped from 2s to under 200ms! Also started experimenting with Redis caching for frequently accessed queries — the performance difference is insane. Backend folks: do you usually optimize first or wait until bottlenecks appear?",
    tags: ["Backend", "Optimization"],
    recSkill: ["Redis Caching", "Database Indexing"],
  },
  {
    id: "6",
    user: "Sophia M.",
    skillset: "Digital Marketing",
    icon: "SM",
    text: "Tried a new strategy for ad campaigns where I focused less on hard selling and more on community building. Instead of ‘Buy now’ ads, I created content like tutorials, challenges, and behind-the-scenes posts. Engagement went up 65%, and actual conversions followed naturally. It’s a reminder that in 2025, trust and authenticity sell way better than shouting discounts every week. Marketers — are you seeing the same trend?",
    tags: ["Marketing", "Community"],
    recSkill: ["Organic Growth Hacks", "Influencer Collabs"],
  },
  {
    id: "7",
    user: "Li Wei",
    skillset: "Data Science",
    icon: "LW",
    text: "Spent the weekend cleaning a messy dataset with over 5 million rows 😅. What shocked me was that nearly 20% of the data had inconsistencies in timezones and formatting. After normalizing everything, the machine learning model accuracy jumped from 72% to 85%! Sometimes the biggest improvements come not from fancy algorithms but just solid data hygiene. Pro tip: always profile your dataset before running models.",
    tags: ["Machine Learning", "Big Data"],
    recSkill: ["Data Cleaning", "Model Optimization"],
  },
  // Ultra-long posts for stress-testing
  {
    id: "8",
    user: "Aisha R.",
    skillset: "Product Management",
    icon: "AR",
    text: "I’ve been reflecting on how product roadmaps can often be a double-edged sword. On one hand, they give stakeholders confidence, alignment, and clarity. On the other hand, they can lock teams into rigid paths that ignore real-time learning. Last quarter, we created a roadmap that stretched 6 months, but by month 2, user feedback made half the items irrelevant. Instead of tossing the roadmap entirely, I tried a flexible approach: keeping high-level goals fixed but letting the actual features and implementations evolve dynamically. The result? We shipped faster, stakeholders still felt informed, and the team had space to experiment. I think product managers need to stop worshipping the roadmap and start treating it as a living document that bends with reality. Would love to hear if anyone else has transitioned away from static roadmaps and what challenges you faced in convincing leadership. Because honestly, some execs still see ‘no roadmap’ as chaos, when in fact it’s agility in action.",
    tags: ["Agile", "Leadership"],
    recSkill: ["Roadmap Flexibility", "Stakeholder Management"],
  },
  {
    id: "9",
    user: "Marcus T.",
    skillset: "Cybersecurity",
    icon: "MT",
    text: "Just finished leading a red team exercise simulating an advanced persistent threat attack, and wow, the results were eye-opening. The team exploited weaknesses not through fancy zero-days but through simple misconfigurations and poor credential hygiene. For example, 3 admins were reusing the same password across multiple services — once breached, it opened up lateral movement like wildfire. Even scarier, sensitive documents weren’t encrypted at rest, meaning anyone with access could extract them directly. This is 2025, and we still underestimate the basics. The lesson for me wasn’t about needing the newest AI-driven defense systems — it was about doubling down on fundamentals like password rotation, least privilege, encryption, and regular auditing. It made me realize that most breaches don’t happen because hackers are geniuses, but because companies are lazy about basics. If you’re running security teams, please: patch systems, train users, and never assume you’re too small to be a target. Cybersecurity is only as strong as the weakest overlooked practice, and in our case, that nearly cost millions.",
    tags: ["Security", "Best Practices"],
    recSkill: ["Red Teaming", "System Hardening"],
  },
];
