export const FeedData = [
  {
    id: "1",
    user: "John Doe",
    skillset: "Graphic Design",
    icon: "JD",
    text: "Design isn’t just about aesthetics — it’s about solving problems. I just wrapped up a project where the client thought they needed a flashy poster, but after digging deeper, it turned out they needed a whole rebrand strategy. Sometimes, the challenge is not creating what’s asked, but uncovering what’s actually needed.",
    tags: ["Public Speaking", "Information Technology"],
    recSkill: [
      { id: "1.1", skill: "Design Kit - Human Interaction" },
      { id: "1.2", skill: "Benching the Instagram" },
    ],
  },
  {
    id: "2",
    user: "Sophia Lee",
    skillset: "Data Science",
    icon: "SL",
    text: "Just deployed my first ML model into production 🚀. The most surprising part wasn’t training accuracy, but how much data cleaning and monitoring mattered after deployment. Lesson learned: data drift is real, and ignoring it is like building a house on quicksand.",
    tags: ["Machine Learning", "Big Data"],
    recSkill: [
      { id: "2.1", skill: "Data Wrangling" },
      { id: "2.2", skill: "Model Deployment" },
    ],
  },
  {
    id: "3",
    user: "Michael B.",
    skillset: "Mobile Development",
    icon: "MB",
    text: "Experimented with React Native and honestly, the cross-platform efficiency is insane. One codebase running smoothly on both iOS and Android felt like cheating. Of course, performance tweaks still matter — animations, images, and navigation must be optimized, but the productivity boost is worth it.",
    tags: ["React Native", "Cross Platform"],
    recSkill: [
      { id: "3.1", skill: "Performance Optimization" },
      { id: "3.2", skill: "UI/UX Consistency" },
    ],
  },
  {
    id: "4",
    user: "Aisha K.",
    skillset: "Marketing",
    icon: "AK",
    text: "Ran an A/B test for email campaigns and the results shocked me. Subject line tweaks outperformed a full redesign of the email body by 4x. Never underestimate the power of the first line your audience reads.",
    tags: ["Digital Marketing", "Analytics"],
    recSkill: [
      { id: "4.1", skill: "Copywriting" },
      { id: "4.2", skill: "Campaign Strategy" },
    ],
  },
  {
    id: "5",
    user: "David R.",
    skillset: "Software Engineering",
    icon: "DR",
    text: "Pair programming has been one of the most underrated tools in my growth. It’s not just about catching bugs — it’s about knowledge transfer. Junior devs learn faster, and senior devs get challenged on assumptions. Code reviews are great, but real-time collaboration levels you up.",
    tags: ["Agile", "Collaboration"],
    recSkill: [
      { id: "5.1", skill: "Pair Programming" },
      { id: "5.2", skill: "Test-Driven Development" },
    ],
  },
  {
    id: "6",
    user: "Emily R.",
    skillset: "UI/UX Design",
    icon: "ER",
    text: "Conducted a usability test yesterday and it reminded me: users don’t read, they scan. Our beautifully written onboarding steps? Ignored. What worked instead? Simple icons and a one-tap skip button. Design for behavior, not assumptions.",
    tags: ["User Research", "Design Thinking"],
    recSkill: [
      { id: "6.1", skill: "Usability Testing" },
      { id: "6.2", skill: "Wireframing" },
    ],
  },
  {
    id: "7",
    user: "Carlos M.",
    skillset: "AI & Robotics",
    icon: "CM",
    text: "Built a chatbot that now handles 70% of customer queries at my startup. The key wasn’t GPT-like smarts — it was just narrowing scope and training on FAQs. Fancy models are cool, but focus beats complexity every time.",
    tags: ["AI", "Automation"],
    recSkill: [
      { id: "7.1", skill: "Natural Language Processing" },
      { id: "7.2", skill: "Automation Scripting" },
    ],
  },
  {
    id: "8",
    user: "Fatima Z.",
    skillset: "Cloud Computing",
    icon: "FZ",
    text: "Migrated a legacy app to AWS this month. Honestly, the hardest part wasn’t the tech — it was convincing management that downtime was necessary. Cloud isn’t just a tech shift, it’s a cultural shift too.",
    tags: ["AWS", "DevOps"],
    recSkill: [
      { id: "8.1", skill: "Cloud Migration" },
      { id: "8.2", skill: "CI/CD Pipelines" },
    ],
  },
  {
    id: "9",
    user: "Marcus T.",
    skillset: "Cybersecurity",
    icon: "MT",
    text: "Just finished leading a red team exercise simulating an advanced persistent threat attack, and wow, the results were eye-opening. The team exploited weaknesses not through fancy zero-days but through simple misconfigurations and poor credential hygiene. For example, 3 admins were reusing the same password across multiple services — once breached, it opened up lateral movement like wildfire. Even scarier, sensitive documents weren’t encrypted at rest, meaning anyone with access could extract them directly. This is 2025, and we still underestimate the basics. The lesson for me wasn’t about needing the newest AI-driven defense systems — it was about doubling down on fundamentals like password rotation, least privilege, encryption, and regular auditing. It made me realize that most breaches don’t happen because hackers are geniuses, but because companies are lazy about basics. If you’re running security teams, please: patch systems, train users, and never assume you’re too small to be a target. Cybersecurity is only as strong as the weakest overlooked practice, and in our case, that nearly cost millions.",
    tags: ["Security", "Best Practices"],
    recSkill: [
      { id: "9.1", skill: "Red Teaming" },
      { id: "9.2", skill: "System Hardening" },
    ],
  },
];
